# .github/workflows/pipeline.yml
name: Daily Stock Pipeline

on:
  schedule:
    - cron: '0 7 * * 1-5'    # 7am UTC, weekdays
  workflow_dispatch:           # manual trigger from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          database_url:  ${{ secrets.DATABASE_URL }}
          finnhub_key:   ${{ secrets.FINNHUB_KEY }}
        #   ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
        run: python StocksLens/data_pipeline/main/main.py